social-login-app:
  oauth:
    facebook:
      clientId: "your-facebook-app-id"
      secret: "your-facebook-secret"
      redirect: "http://localhost:3000/"
      api: "https://graph.facebook.com/v6.0"
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 1800

logging:
  level:
    com: DEBUG
    org: DEBUG
